# Generated by Django 3.0.6 on 2021-02-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estampa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField()),
                ('tema', models.CharField(choices=[('1', 'ARTE'), ('5', 'OTRO'), ('4', 'PELICULAS'), ('2', 'MUSICA'), ('3', 'TECNOLOGIA'), ('0', 'DEPORTE')], max_length=1, verbose_name='TEMA')),
                ('popularidad', models.CharField(choices=[('0', 'BAJA'), ('1', 'MEDIA'), ('2', 'ALTA')], max_length=1, verbose_name='Popularidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empleado')),
                ('stock', models.IntegerField()),
                ('num_ventas', models.IntegerField()),
                ('descontino', models.BooleanField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'verbose_name': 'Estampa',
                'verbose_name_plural': 'Estampas',
            },
        ),
    ]
