# Generated by Django 3.0.6 on 2021-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estampa',
            name='descontino',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='estampa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='estampa',
            name='popularidad',
            field=models.CharField(choices=[('2', 'ALTA'), ('1', 'MEDIA'), ('0', 'BAJA')], max_length=1, verbose_name='Popularidad'),
        ),
        migrations.AlterField(
            model_name='estampa',
            name='tema',
            field=models.CharField(choices=[('1', 'ARTE'), ('0', 'DEPORTE'), ('4', 'PELICULAS'), ('2', 'MUSICA'), ('3', 'TECNOLOGIA'), ('5', 'OTRO')], max_length=1, verbose_name='TEMA'),
        ),
    ]
