# Generated by Django 3.0.6 on 2021-03-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20210303_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estampa',
            name='popularidad',
            field=models.CharField(choices=[('1', 'MEDIA'), ('0', 'BAJA'), ('2', 'ALTA')], max_length=1, verbose_name='Popularidad'),
        ),
        migrations.AlterField(
            model_name='estampa',
            name='tema',
            field=models.CharField(choices=[('0', 'DEPORTE'), ('5', 'OTRO'), ('2', 'MUSICA'), ('1', 'ARTE'), ('4', 'PELICULAS'), ('3', 'TECNOLOGIA')], max_length=1, verbose_name='TEMA'),
        ),
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(max_length=50, verbose_name='Comprador')),
                ('valor', models.IntegerField()),
                ('comprado', models.BooleanField(default='False')),
                ('talla', models.CharField(choices=[('3', 'XL'), ('0', 'S'), ('1', 'M'), ('2', 'L')], max_length=1, verbose_name='Talla')),
                ('color', models.CharField(choices=[('5', 'AMARILLO'), ('3', 'NEGRO'), ('2', 'BLANCO'), ('4', 'VERDE'), ('1', 'ROJO'), ('0', 'AZUL')], max_length=1, verbose_name='Color')),
                ('material', models.CharField(choices=[('0', 'ALGODON'), ('1', 'POLIESTER'), ('2', 'TRI-BLEND')], max_length=1, verbose_name='Material')),
                ('estampa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Estampa')),
            ],
            options={
                'verbose_name': 'Camiseta',
                'verbose_name_plural': 'Camisetas',
            },
        ),
    ]
