# Generated by Django 3.0.6 on 2021-03-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20210303_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='color',
            field=models.CharField(choices=[('3', 'NEGRO'), ('2', 'BLANCO'), ('1', 'ROJO'), ('0', 'AZUL'), ('4', 'VERDE'), ('5', 'AMARILLO')], max_length=1, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='material',
            field=models.CharField(choices=[('0', 'ALGODON'), ('2', 'TRI-BLEND'), ('1', 'POLIESTER')], max_length=1, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='talla',
            field=models.CharField(choices=[('1', 'M'), ('2', 'L'), ('0', 'S'), ('3', 'XL')], max_length=1, verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='estampa',
            name='popularidad',
            field=models.CharField(choices=[('0', 'BAJA'), ('1', 'MEDIA'), ('2', 'ALTA')], max_length=1, verbose_name='Popularidad'),
        ),
        migrations.AlterField(
            model_name='estampa',
            name='tema',
            field=models.CharField(choices=[('2', 'MUSICA'), ('3', 'TECNOLOGIA'), ('1', 'ARTE'), ('5', 'OTRO'), ('0', 'DEPORTE'), ('4', 'PELICULAS')], max_length=1, verbose_name='TEMA'),
        ),
    ]
