# Generated by Django 3.1.4 on 2020-12-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estampa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estampa',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estampa',
            name='tema',
            field=models.CharField(choices=[('5', 'OTRO'), ('1', 'ARTE'), ('2', 'MUSICA'), ('4', 'PELICULAS'), ('3', 'TECNOLOGIA'), ('0', 'DEPORTE')], max_length=1, verbose_name='TEMA'),
        ),
    ]
